// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dbvshbjyebszbiywqifq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRidnNoYmp5ZWJzemJpeXdxaWZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5ODQ1NDgsImV4cCI6MjA1NTU2MDU0OH0.BDlvi5FKSXjgPNXjMoxiRO-xWaZLC6H-9N2FgHYVYUw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);